version: '3.7'

services:

  nginx:
    restart: always
    image: 'docker.io/nginx:1.17'
    networks:
      - nginx_default
      - default
    restart: 'always'
    volumes:
      - '/home/platypus/Code/platformplatform/pypi-mirror/data/web/:/usr/share/nginx/html:ro'
      - '/home/platypus/Code/platformplatform/pypi-mirror/config/nginx:/etc/nginx/conf.d'
      
networks:
  nginx_default:
    external: true