version: '3.7'

services:
  registry:
    image: bitnami/harbor-registry:1
    restart: always
    volumes:
      - registry_data:/storage
      - ${PWD}/harbor/config/registry:/etc/registry:ro
  registryctl:
    image: bitnami/harbor-registryctl:1
    restart: always
    environment:
      - CORE_SECRET=CHANGEME
      - JOBSERVICE_SECRET=CHANGEME
    volumes:
      - registry_data:/storage
      - ${PWD}/harbor/config/registry:/etc/registry:ro
      - ${PWD}/harbor/config/registryctl:/etc/registryctl:ro
  postgresql:
    image: bitnami/postgresql:11
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=registry
    volumes:
      - postgresql_data:/bitnami/postgresql
  core:
    image: bitnami/harbor-core:1
    restart: always
    depends_on:
      - registry
      - chartmuseum
    environment:
      - CORE_KEY=change-this-key
      - _REDIS_URL=redis:6379,100,
      - SYNC_REGISTRY=false
      - CHART_CACHE_DRIVER=redis
      - _REDIS_URL_REG=redis://redis:6379/1
      - PORT=8080
      - LOG_LEVEL=info
      - EXT_ENDPOINT=http://reg.mydomain.com
      - DATABASE_TYPE=postgresql
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_SSLMODE=disable
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://core:8080/service/token
      - HARBOR_ADMIN_PASSWORD=bitnami
      - CORE_SECRET=CHANGEME
      - JOBSERVICE_SECRET=CHANGEME
      - ADMIRAL_URL=
      - WITH_NOTARY=False
      - WITH_CLAIR=False
      - WITH_CHARTMUSEUM=True
      - CHART_REPOSITORY_URL=http://chartmuseum:8080
      - CORE_URL=http://core:8080
      - JOBSERVICE_URL=http://jobservice:8080
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - READ_ONLY=false
      - RELOAD_KEY=
    volumes:
      - core_data:/data
      - ${PWD}/harbor/config/core:/etc/core
  portal:
    image: bitnami/harbor-portal:1
    restart: always
    depends_on:
      - core
  jobservice:
    image: bitnami/harbor-jobservice:1
    restart: always
    depends_on:
      - redis
      - core
    environment:
      - CORE_SECRET=CHANGEME
      - JOBSERVICE_SECRET=CHANGEME
      - CORE_URL=http://core:8080
    volumes:
      - jobservice_data:/var/log/jobs
      - ${PWD}/harbor/config/jobservice:/etc/jobservice:ro
  redis:
    image: bitnami/redis:5.0
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  harbor-nginx:
    image: bitnami/nginx:1.16
    networks:
      - default
      - nginx_default
    restart: always
    volumes:
      - ${PWD}/harbor/config/proxy:/opt/bitnami/nginx/conf:ro
    depends_on:
      - postgresql
      - registry
      - core
      - portal
  chartmuseum:
    image: bitnami/chartmuseum:0
    restart: always
    environment:
      - CACHE=redis
      - CACHE_REDIS_ADDR=redis:6379
      - CACHE_REDIS_DB=1
      - DEPTH=1
      - PORT=8080
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/bitnami/data
      - ALLOW_OVERWRITE=true
      - INDEX_LIMIT=0
    volumes:
      - chartmuseum_data:/bitnami/data
volumes:
  registry_data:
    driver: local
  core_data:
    driver: local
  jobservice_data:
    driver: local
  postgresql_data:
    driver: local
  chartmuseum_data:
    driver: local

networks:
  nginx_default:
    external: true