version: '3.7'

services:
# MinIO
  minio:
    image: 'bitnami/minio:latest'
    networks:
      - nginx_default
      - default
    restart: always
    environment:
      - MINIO_ACCESS_KEY=${MINIO_PASSWORD_1}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD_2}
    volumes:
      - minio_data:/data
#      - /home/platypus/Code/platformplatform/minio/data:/data

volumes:
  minio_data:

networks:
  nginx_default:
    external: true
