version: '3.7'

services:
# MinIO
  minio:
    image: 'bitnami/minio:latest'
    networks:
      - nginx_default
      - default
    restart: always
    env_file:
      - .env
    volumes:
      - minio_data:/data

networks:
  nginx_default:
    external: true

volumes:
  minio_data:
