version: '3'

services:
# MinIO
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    env_file:
      - .env
    volumes:
      - /home/platypus/Code/platformplatform/minio/data:/data