version: '3'

services:
# MinIO
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: testingtesting123
      MINIO_SECRET_KEY: testingtesting123
    command: server /data
    volumes:
      - ./data:/data
