version: '3'

services:
  minio:
    image: 'bitnami/minio:latest'
    env_file:
      - .env

  splitter:
    image: goal86sg/chopchop:latest 
    entrypoint: ["/app/wait-for-it.sh" , "platformplatform_minio_1:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/script.sh"]
    restart: always
    environment: 
      - TX=TRUE
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc
      - chopchop:/app/tmp

  joiner:
    image: goal86sg/chopchop:latest 
    entrypoint: ["/app/wait-for-it.sh" , "platformplatform_minio_1:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/script.sh"]
    restart: always
    environment: 
      - RX=TRUE
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc
      - chopchop:/app/tmp

  diode:
    image: goal86sg/chopchop:latest 
    entrypoint: ["/app/wait-for-it.sh" , "platformplatform_minio_1:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/diode.sh"]
    restart: always
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc

  janitor:
    image: goal86sg/chopchop:latest 
    entrypoint: ["/app/wait-for-it.sh" , "platformplatform_minio_1:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/janitor.sh"]
    restart: always
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc

volumes: 
  mc_config:
  chopchop: