version: '3.7'

services:

  splitter:
    image: goal86sg/chopchop:latest 
    entrypoint: ["/app/wait-for-it.sh" , "platformplatform_minio_1:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/script.sh"]
    restart: always
    environment: 
      - TX=TRUE
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc
      - ${PWD}/chopchop/tmp:/app/tmp

volumes: 
  mc_config: